### ISSUE TITLE
[BUG] Imviz: load data after imviz.app does not show last loaded data

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1126]
Workflow to reproduce this:

1. Load Imviz and run `imviz.app` without loading anything.
2. Load first data. See it displayed fine.
3. Load second data. It is supposed to show up in viewer but first data is still there. Forcing `show_in_viewer=True` does not change anything. When you inspect `imviz.default_viewer.state.layers`, both layers `.visible` attributes are `True` and `.alpha` set to 1.0. What is going on here? The only thing I noticed is I have to set `imviz.default_viewer.allow_duplicate_data = True` to make this problem go away but I don't know if that is the right fix. Somehow this workflow triggers [glue/viewers/common/viewer.py#L192](https://github.com/glue-viz/glue/blob/55428b0524b642e364a7039973c0629f1d62e257/glue/viewers/common/viewer.py#L192) for the second load.
4. Compass is now confused because it thinks second data is being shown. This also affects blinking, which makes the same assumption as Compass.

```python
for lyr in imviz.default_viewer.state.layers:
    print(lyr.layer.label, lyr.visible, lyr.alpha)
```

If you blink them, they will be back in sync again.

The behavior above might be a bug because it is inconsistent with what goes on if you swap the order of operation as follows:

1. Load imviz but do not run `imviz.app` yet.
2. Load first data and load second data.
3. Run `imviz.app` to show viewer. Second data is now shown.
4. Compass is shows second data as expected. Blink also works as expected.

I tried digging around in `jdaviz/app.py`, `glue_jupyter/view.py`, and `glue/viewers/common/viewers.py` but did not find any obvious bug to fix. The key to fixing this is a way for me to know what is actually being display on the top. The current algorithm "blink"is using is unreliable.

https://github.com/spacetelescope/jdaviz/blob/27ff60c11482191bf66e5a626df972d6fa633e57/jdaviz/configs/imviz/plugins/viewers.py#L142

[🐱](https://jira.stsci.edu/browse/JDAT-2166)

**Comment by astrofrog** [comment]
I've started investigating this, I'll report back soon!

**Comment by astrofrog** [comment]
I haven't got to the bottom of this but from what I can see so far this is due to some kind of race condition where by the time of the last image draw in imviz, the links aren't fully set up.

One issue I found is that when loading the second dataset, ``Application._link_new_data`` in jdaviz is being called and is only linking one of the pixel axes. Should we even be calling that method in imviz given that imviz has its own code to set up links? I don't *think* this is the cause of the issue here, but it does cause unnecessary redraws/flashing of the image when loading the second dataset so would be worth fixing anyway. It might even be the cause of the present issue.

I'll try and continue investigating on Tuesday unless someone beats me to it. Basically we need to check that the links are completely set up before add_data is called on the viewer.

**Comment by pllim** [comment]
Imviz never uses any of the linking in app, so I think you can safely not do that for Imviz. TBH I have no idea what the purpose of linking at app level; that was added before my time.
