### ISSUE TITLE
Update button styles and groupings

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#134]

**Comment by Jenneh** [comment]
<img width="661" alt="Screen Shot 2020-06-08 at 10 35 51 AM" src="https://user-images.githubusercontent.com/2945880/84043424-42c92380-a974-11ea-8600-965a7326f84c.png">

**Comment by Jenneh** [comment]
Right now the icons are just spattered across the toolbar. Button groups help group actions that are related to each other and separate actions that are not. Outlining the buttons will help with this differentiation rather than having floating icons. Use the tile button style—see “edit” example.

See more information on the spec: https://www.stsci.edu/~jkotler/Spectra/#g=1&p=toolbars
