### ISSUE TITLE
Set padding above the plot so the hamburger menu takes up less space

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#139]

**Comment by Jenneh** [comment]
<img width="197" alt="Screen Shot 2020-06-08 at 10 21 22 AM" src="https://user-images.githubusercontent.com/2945880/84041660-17453980-a972-11ea-8603-816bfa12279c.png">
<img width="109" alt="Screen Shot 2020-06-08 at 10 21 19 AM" src="https://user-images.githubusercontent.com/2945880/84041662-17453980-a972-11ea-9613-fc5ad09e0b20.png">


Currently the hamburger button has a lot of extra padding to make it work better for a touch screen. Because of this it overlaps with the graph blocking information. We need to remove some of this padding, or reconsider the design.
