### ISSUE TITLE
Find solution to front-end file browser ("IMPORT +" button should open file dialog)

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/jdaviz#156]
We are limited in the browser in that for security browsers do not have access to the host file system. Traditionally, what happens when you choose a file in a browser is that that file gets uploaded to the browser and then used in a local browser file system. We can't do that with our scientific data (there's a limit on the size of data files that can be uploaded to the browser). More complicated examples stream data to a back-end server and stores and parses from there. The way we deal with this is that the jupyter kernel is our "back-end server". 

Currently, we can pass a path to jupyter kernel and have all data loading happen there, but then the user has to provide an annoying (and perfectly accurate) file path. An alternative requires some hoop-jumping that has been done in [ipywidgets](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#File-Upload), but provides a file browser chooser.

Another alternative is to construct our own file chooser using vuetify widgets.

**Comment by eteq** [comment]
Hmm, so I think the ipywidgets-like approach is the most promising one to me: that is, the approach there is to "upload" a file into memory, which you can then wrap in a `io.BytesIO` to have it look like a file for downstream processing by `jdaviz`/`specutils`/etc. That may not work right now because not all loaders we have support file-like objects, but they *should*, since we want to eventually support URL streaming, etc.

As I see it that approaches has the advantage that:

1. It gives a native (browser-backed) file picker which will replicate the look-and-feel familiar to the user
2. It provide for "free" a way to have a workflow where the jupyter kernel is running elsewhere and the user wants to upload a local file.
3. It forces us to make sure we properly support file-like objects as inputs

The big disadvantages I see are is:
1. Two different code paths for loading a "local file" - one based on path and the other based on the above
2. Sort of a corollary: it won't work for datasets too large to fit in memory that otherwise can be "streamed". (although one can still work around that with memmapping perhaps?)  I'm not sure we actually have any examples of this right now but it could come up in the future.

**Comment by mariobuikhuizen** [comment]
With ipyvuetify it is now possible to upload files without a file size limit:

https://github.com/mariobuikhuizen/ipyvuetify/tree/master/examples/extra

This widget exposes the file as a file like object and has random access support. This makes it possible to read only parts of a file instead of the whole file.
