### ISSUE TITLE
Decide how to deal with error raises and uncaught exceptions

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#170]
We should discuss and decide on a standard way of dealing with errors within the application.   Some pieces of code raise errors when something goes wrong or inputs don't match.  Other pieces have assert statements.  Other pieces use the snackbar message to indicate errors.  Raises and asserts are fine within a notebook, where they will be displayed, but will not work when the application is run in desktop mode or in the web.  The application will simply crash with the error buried somewhere else.   For those interface modes, we probably want to catch the error and display an error message nicely in the application, similar to what is done already with some plugins and the snackbar.   For easier development I think a standard method should be decided upon and adopted for all interfaces.  Are raises and asserts ok or should we move to catching all errors/raises and informing the user via the snackbar?  

I recently ran into this when I loaded an old JWST spectrum file in the web, using the `SpecViz.load_data` helper, which crashed inside Spectrum1D with an uncaught exception.  This error was buried and the only reason I saw it was because of an extra debug block I added capturing output.

**Comment by havok2063** [comment]
This is a pseudo-blocker since it's not clear how I should handle things in new code I write.

**Comment by nmearl** [comment]
> Are raises and asserts ok or should we move to catching all errors/raises and informing the user via the snackbar?

We should not be using asserts for control flow anywhere -- we should always raise clear exceptions. Snackbar notifications are temporary and definitely should not be the only place an exception propagates. We should always ensure exceptions are raised _along with_ appropriate user-facing UI notifications like snackbars.

We've had a few discussions concerning this already, but the best way to handle exception propagation so its well in both the notebook and web context is by using the ipywidget [`Output`](https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html) widget, which essentially can act to store information that would otherwise be printed to stdout, and we can handle when and where the output is piped.

**Comment by havok2063** [comment]
That makes sense to me.   I'll use raises within internal methods and aim to catch them at higher levels so they don't trigger crashes.  I like the `Output` widget idea.  I could imagine a general error dialog modal that captures and displays errors and tracebacks from across the application.  The snackbar could be used as an immediate warning as well.
