### ISSUE TITLE
Region appears far from cursor

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#218]
Region sometimes appears in upper left corner rather than where cursor is located for subset selection
in CubeViz cube viewer, called from notebook.  Here is an example (grey circle at upper left, rather than centered on source:
![region_displaced](https://user-images.githubusercontent.com/44263689/89459899-725b9880-d737-11ea-9968-06b52ba9b8b1.png)

**Comment by nmearl** [comment]
@astrofrog any ideas on this?

**Comment by PatrickOgle** [comment]
Also happens (only happens?) after resizing plot window.

**Comment by maartenbreddels** [comment]
FYI, this is fixed in https://github.com/glue-viz/bqplot-image-gl/pull/31 and should be fixed in bqplot-image-gl 0.6.0 (releasing this soon).


cc @eteq 
I think this should go into the requirements of glue-jupyter, and if it does, this should be reflected in the requirements of jdaviz. I'll open a PR for glue-jupyter for this, and refer back to this to track it.

**Comment by maartenbreddels** [comment]
Correction, this requires 0.6.1, 0.6.0 was a bad release.
