### ISSUE TITLE
Data menu broken in Imviz extra viewer on Lab

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#2581]
I see this on main currently so it was not caused by whatever the rotation PR is doing. Only see it on Lab. Works fine on Notebook in the same env. Using WSL2 (Debian/Ubuntu) on Windows 10/11, with Chrome browser (but @kecnry could reproduce it in OSX). cc @mariobuikhuizen 

Workflow to reproduce:

1. Run Imviz example notebook and load both images.
2. Go to the cell that says `imviz.show()` but do not run it yet. Right click on it and select "Create New View for Cell Output".
3. Now run `imviz.show()`.
4. Use the "popped out" version of the Imviz viewer.
5. Make a new viewer. Load either image A or B. See that Data menu in `imviz-1` misbehaves.
6. See screenshots. The screenshots also have markers loaded but you don't need those to reproduce the bug.

<img width="536" alt="Screenshot 2024-01-17 112025" src="https://github.com/spacetelescope/jdaviz/assets/2090236/2fe668b3-d27a-4ad2-9fbb-cbf9e7b6b172">

imviz-0 is okay:

![Screenshot 2023-11-28 145235](https://github.com/spacetelescope/jdaviz/assets/2090236/25f51290-a598-448d-bd72-0e58d426489b)

but imviz-1 is broken in Lab but not Notebook:

![Screenshot 2023-11-28 145326](https://github.com/spacetelescope/jdaviz/assets/2090236/b317b460-1b69-4302-b43b-d59269e40d25)

[🐱](https://jira.stsci.edu/browse/JDAT-4021)

**Comment by pllim** [comment]
Mario found a workaround and I confirmed that doing this before starting the notebook/lab server fixes my use case:

`export JUPYTER_WIDGETS_ECHO=False`

❗ The catch: ipypopout is disabled when this is used.

Mario's comments as follows.

<hr/>

I’ve narrowed the issue down to having 2 views in the notebook (which is the case with using sidecar in lab, but can also be achieved with have two cells with `imviz.show()`) and the `echo-comm-message` functionality (introduced for `ipypopout`).

I can also reproduce it in classic notebook with two cells with `imviz.show()`.

Running Lab with it disabled, fixes the issue: `JUPYTER_WIDGETS_ECHO=False jupyter lab`

(but then `ipypopout` won’t work)

I think it should be fixed in `ipywidgets`. Turning it off validated my theory.

**Comment by mariobuikhuizen** [comment]
After looking further into it, the echo issue is not the only problem.

Having two views with a `<v-menu :close-on-content-click="false" ...>` ([line](https://github.com/spacetelescope/jdaviz/blob/8edbdf05b04a201f0fe394082ae95371394f4fb4/jdaviz/components/viewer_data_select.vue#L3)), makes them close anyway when content is clicked, because for one of the menu's this is a "click outside", which closes the menu and updates the the shared model. This also causes an update of the app.state in the kernel.
This happens after the method `data_item_visibility` ([line](https://github.com/spacetelescope/jdaviz/blob/8edbdf05b04a201f0fe394082ae95371394f4fb4/jdaviz/app.vue#L93)) is called, so the state change that happened with that is overwritten with the old state.
