### ISSUE TITLE
BUG: WCS to Pixels to WCS gives wrong reference data

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#2724]
This is a follow-up of:

* #2179 

And discovered in:

* #2712

Workflow to reproduce:

1. Use the `ImvizDitheredExample.ipynb` example notebook. Load both data.
2. Link by WCS on the Orientation plugin.
3. Click the "N-up E-left" icon so now the images in first viewer is aligned by N-up E-left.
4. Create a second viewer and load the first image only.
5. With second viewer (`imviz-1`) selected in Orientation, click on the "N-up E-right" icon so now the second viewer image is aligned by N-up E-right.
6. Now select "Pixels" in Orientation. Both viewers will go back to pixel linking and no longer appear rotated.
7. Now click "WCS" again in Orientation. See that both images do not go back to being aligned by one of the 3 possible WCS layers (see screenshot below). Despite that, when you blink, the stars still aligned (despite the exposures being dithered) as if #2179 never happened.

![Screenshot 2024-02-22 162201](https://github.com/spacetelescope/jdaviz/assets/2090236/8e4590d0-14c5-46e4-8da9-bf18e54fec9e)

[🐱](https://jira.stsci.edu/browse/JDAT-4224)

**Comment by bmorris3** [comment]
That's confusing, especially because I made sure this worked when I last touched this code. 

I followed your example, and I see the bug too, and if you do: 
```python
for viewer_name, viewer in imviz.viewers.items():
    print(
        viewer_name, 
        viewer._obj.state.reference_data.label, 
        viewer._obj.state.linked_by_wcs
    )
```
You see
```
imviz-0 acs_47tuc_1[SCI,1] True
imviz-1 acs_47tuc_1[SCI,1] True
```
but as you mentioned, the data are linked by the WCS on the data, rather than the WCS in the WCS-only layer. 

Did someone change the logic for when to change reference data on link-type change?

**Comment by pllim** [comment]
> Did someone change the logic

So many things were merged in around that time, I can't remember what is what. Might be an accidental regression when a rebase happen somewhere too.

**Comment by pllim** [comment]
@bmorris3 , I think I know where the bug is but I don't understand the distinction between `default_reference_layer` and `refdata` in `link_image_data`. I thought about adding a `elif link_type == 'wcs' and old_link_type == 'pixels':` after this block but not sure how to do it properly. Any advice? Thanks!

https://github.com/spacetelescope/jdaviz/blob/4907826e6538e406cb670c64dc0b2c19aed21cb8/jdaviz/configs/imviz/helper.py#L591

**Comment by bmorris3** [comment]
`default_reference_layer` in all cases (without deleting Data) is just the first loaded Data. It's useful here because the WCS-only layers are defined wrt the first loaded Data. `refdata` comes from `get_reference_image_data`, which may be None, or the first loaded image, or the data you've set as reference data in the workflow.
