### ISSUE TITLE
[BUG] Click-to-center broken when WCS-linked

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#2749]
### Jdaviz component

Imviz

### Description

If you have multiple images linked by WCS and have a layer on top that isn't the reference data, clicking will still center based on the pixels of the reference data and thus center on the wrong place.

### How to Reproduce

1. Run the Imviz example notebook
2. Select pan zoom tool, click somewhere with dataset B on top/active.

[🐱](https://jira.stsci.edu/browse/JDAT-4337)

**Comment by pllim** [comment]
Did you blink at all? I need to know if you actually have 2 visible layers, or just 1.

**Comment by rosteen** [comment]
I did not blink prior to this.

**Comment by pllim** [comment]
@rosteen , does https://github.com/spacetelescope/jdaviz/pull/2750 make it better?

I think it is going to feel a bit awkward when things are linked by WCS and you click off the actual bounding box, because GWCS might not round-trip back and forth perfectly between reference WCS and image WCS. But hopefully you won't just randomly pan to the middle of nowhere.
