### ISSUE TITLE
Can't plot contours from Moment Map Plugin over cube viewer

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#318]
Here is the workflow

1. Read in continuum-subtracted MANGA data cube
2. Select subset in spectrum viewer
3. Create Moment 0 map in Moment Maps Plugin
4. Select Flux Cube and  Moment0 Data Set in Cube viewer
5. Select Moment0 Layer
6. Activate Contours

Contours for the same Moment0 product can be viewed in a separate image viewer with no problem,
but they don't appear in the cube viewer. The same contour levels are generated in the cube viewer, 
but they aren't visible:

![manga_moment1_contours](https://user-images.githubusercontent.com/44263689/94845160-4bdf7400-03ed-11eb-9cd3-ebe14573b66c.png)

**Comment by PatrickOgle** [comment]
Bug persists in jdaviz v1.1

**Comment by PatrickOgle** [comment]
Bug is reproducible with JWST NIRSpec IFU cube and above MANGA cube.  However, I have found a workaround for it:
1) deselect data cube
2) select moment map
3) select data cube
4) Repeat the workflow in the Description, and now the contours can be seen.

It seems like the contours are only visible when the moment map is the first layer in the list of layers.  Changing the opacity doesn't help.

**Comment by javerbukh** [comment]
Contours still work in the following situations:

- A single data is loaded into one of the cubeviz viewers and contours are turned on
-  In Imviz, contours work as expected. That means that two images on two different layers can be active, with contours from one appearing on the other. This happens even without turning the bitmap off, which is what the documentation tells you to do.

Contours **do not** work in the following situations:

- As described in the documentation in the above comment. The contours of the IVAR portion of a cube cannot be superimposed on the FLUX portion in a single image viewer. This is functionality that worked previously (as of the May 25th, 2021 comment above).
- The same is true for the resulting data from the plugins. Moment map data (as described in this ticket) cannot have its contours plotted over other moment map data or cube data. The same thing is true with the smoothing plugin and collapse plugin.

My question is why contour works as expected in imviz but not in cubeviz? Imviz uses `NDData` while cubeviz uses `Spectrum1D` except with the moment maps plugin, which uses `CCDData`. It seems like the only types of data which can be used for superimposing contours on different layers is `NDData`. Is that something that needs to be fixed in glue-astronomy? I seem to remember contours working in cubeviz (as described in the documentation) when we were using `Spectral-Cube`, so that would be my best guess, but any further input or guidance would be appreciated!

**Comment by javerbukh** [comment]
I tried linking the data in cubeviz, still no effect.
```
from glue.core.link_helpers import LinkSame
dc = viz.app.data_collection
links_list = [LinkSame(dc[num - 1].component_ids()[1], dc[num].component_ids()[1]) for num in range (1, len(viz.app.data_collection))]
dc.set_links(links_list)
```

**Comment by javerbukh** [comment]
After loading data into cubeviz, I ran the moment map plugin twice (0 and 1) and loaded those data into fits files. I then loaded those files into imviz to see if they would work there, and after linking them by pixels, it worked! Contours of one data were able to be superimposed onto another data.

**Comment by astrofrog** [comment]
@javerbukh you were close with the linking comment above - once the moment map is created you need to link the x/y axes, so two links. You also have to be careful with the axis numbering for the cube vs moment map. Assuming your data is called ``data`` and the moment map is called ``moment``, you need to do:

```
from glue.core.link_helpers import LinkSame
viz.app.data_collection.add_link(LinkSame(cube.pixel_component_ids[1], moment.pixel_component_ids[0]))
viz.app.data_collection.add_link(LinkSame(cube.pixel_component_ids[2], moment.pixel_component_ids[1]))
```

With this, I can then overplot the contours on top of the cube and slice through the cube:

![Peek 2022-03-08 17-04](https://user-images.githubusercontent.com/314716/157288412-3a856ae3-18df-4bb1-bb0c-fbdbcac0c4d2.gif)

I have to stop for the day so happy for someone else to open a PR to do this (I was experimenting by setting the links in the notebook). Otherwise I can open a PR later this week if no one has time sooner.

**Comment by javerbukh** [comment]
Thank you so much for looking into it! Glad you were able to confirm what it was, I will absolutely get started on a PR!
