### ISSUE TITLE
Helper classes use old styling

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#333]
The helpers still use the old styling (SpecViz, CubeViz, MosViz). These should be updated to our new styling (Specviz, Cubeviz, Mosviz)

**Comment by eteq** [comment]
A few folks discussed this a bit out-of-band, and here's the rough summary:

* This was discussed "somewhere" (we couldn't remember where) in the past and at the time the thinking was that the helpers should be CamelCase since they are Python classes.
* After a bit more discussion the feeling was that it's not "Spec viz" it's "Specviz", so camel-case does not apply.  And anyway it's better to try to be consistent since a lot of this subtleties might be lost on users *anyway*.  So we should do what @dtn5ah says here.
* Relatedly, we agreed the old names shall be deprecated but not removed immediately.

To do the deprecation, I'd suggest we change the actual class names immediately to the new styling, but make sub-classes with the old styling that produce a `DeprecationWarning` when the user initializes one of them . Note that `astropy` has an easy deprecation decorator: https://docs.astropy.org/en/stable/api/astropy.utils.decorators.deprecated.html, which I think would allow something as easy as:
```
@deprecated('1.2', alternative='Specviz')
class SpecViz(Specviz):
    pass
```

**Comment by pllim** [comment]
Probably subset of #178
