### ISSUE TITLE
Implement histogram-style (steps, not real histogram) plots for specviz

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#385]
This was discussed in several places in #133 but I'm now realizing we never broke out an issue to specifically do this.  

The goal here is to implement "histogram-style" plots instead of "line plots" - i.e., have the points on the spectrum be plotted as the center of a "box"-like plot instead of joining the segments directly as a line.  For optical spectra this is typically more physical because they are closer to the concept of "flux in boxes" vs "samples from a continuous signal".

Not everyone agrees on what I just said there, so for this issue that should be an *option*.  After this is implemented we can discuss whether it should be the default (which is what I advocated for in #133, but others were less convinced.)

[🐱](https://jira.stsci.edu/browse/JDAT-601)

**Comment by nancymac519** [comment]
The "histogram-style" plot mode is essential; please implement. It's the most realistic way to view any data that are binned into pixels. i agree with eteq that it should be the default; I used to get really tired of nagging students to use it with IRAF. 

R calls this plot style "step plot" or "stair step" plot, a much better term than "histogram," which properly refers to a completely different type of graph.

I'm not yet a SpecViz user, and will not be a consistent user until this is implemented, but i would like to be. Thanks!

**Comment by karlglazebrook** [comment]
Found this when I was seeing if anyone else had requested this.

Yes this is the superior way to plot spectra, as they contain pixels.

In matplotlib the command would be `plt.step(wav, flux, where='mid')` or plt.plot(..., linestyle='steps-mid')

**Comment by nancymac519** [comment]
Thanks! Yes, I also requested this.

R has a plot type (in the 'plot' package) "s" for stair steps.

________________________________________
From: Karl Glazebrook ***@***.***>
Sent: Tuesday, November 9, 2021 2:37 AM
To: spacetelescope/jdaviz
Cc: Morrison, Nancy D.; Comment
Subject: [EXTERNAL] Re: [spacetelescope/jdaviz] Implement histogram-style plots for specviz (#385)

Found this when I was seeing if anyone else had requested this.

Yes this is the superior way to plot spectra, as they contain pixels.

In matplotlib the command would be plt.step(wav, flux, where='mid') or plt.plot(..., linestyle='steps-mid')

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspacetelescope%2Fjdaviz%2Fissues%2F385%23issuecomment-963886870&data=04%7C01%7Cnancy.morrison%40utoledo.edu%7C6aec760f27bf46a78c0408d9a353b7cb%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637720402249164606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ePYTpCgbl9pEv4QVflmHq2GyWJ6BbjXFwqlNqr5sGiQ%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASF32JDTTCHCNBMCMIAYYILULDFRZANCNFSM4WBBSYMA&data=04%7C01%7Cnancy.morrison%40utoledo.edu%7C6aec760f27bf46a78c0408d9a353b7cb%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637720402249174601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z3f%2FMQ4g1DTKRCYFwMgrC%2FQ5DYr5qBrwQPpjyQDj%2F2E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnancy.morrison%40utoledo.edu%7C6aec760f27bf46a78c0408d9a353b7cb%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637720402249174601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G2uz1gVYZEhBmfpLTHGcTEcPSwfNStwt61lkwSGyL4c%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnancy.morrison%40utoledo.edu%7C6aec760f27bf46a78c0408d9a353b7cb%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637720402249184596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JSztzaHOATsihTmEb8%2FycAaZg0Z%2Ft1SF1Vu5YnUNy8k%3D&reserved=0>.

**Comment by PatrickOgle** [comment]
I disagree that this should be default.  For high SNR spectra with thousands of wavelength bins, it adds clutter.
It should definitely be an option.
