### ISSUE TITLE
Issue with viewer size

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#49]
I tried the latest version of jdaviz today with the cubeviz layout and ran into the issue that I'm unable to see the profile viewer because the image viewer always auto-adjusts to fill the browser window (even if I change the browser font size etc):

![Screenshot from 2019-12-02 17-08-50](https://user-images.githubusercontent.com/314716/69979690-a89ca480-1526-11ea-9162-587691a694ea.png)

**Comment by nmearl** [comment]
This is because the default css for the bqplot object is `100hv`, meaning it will responsively take up the hole height. The profile view _is there_, it's just below the screen (and scrolling isn't set to activate).

Traditionally, we'd just set the height of the bqplot object to `100%`, which would stretch it to be the height of its parent container (and that contained has knowledge of whether it's a split view or a full view). But for some reason, this does not work with the bqplot css, so we're stuck with this for the moment until I figure out how to get around it. 😅

**Comment by nmearl** [comment]
This should no longer be an issue. Feel free to reopen or open a new issue.
