### ISSUE TITLE
with_spectral_unit doesn't work on Spectrum1D objects retrieved from CubeViz

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#499]
1) Load JWST s3d spectral cube into Cubeviz
2) Create subset by circular region selection
3) spectrum_subset1_untrimmed = cubeviz.app.get_data_from_viewer('spectrum-viewer')['Subset 1']
4) spectrum_subset1_untrimmed = spectrum_subset1_untrimmed.with_spectral_unit(u.um)

Error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-2161a6d4c820> in <module>
     16 
     17 
---> 18 spectrum_subset1_untrimmed = spectrum_subset1_untrimmed.with_spectral_unit(u.um)

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/specutils/spectra/spectrum_mixin.py in with_spectral_unit(self, unit, velocity_convention, rest_value)
    211 
    212         """
--> 213         new_wcs, new_meta = self._new_spectral_wcs(
    214             unit=unit,
    215             velocity_convention=velocity_convention or self.velocity_convention,

~/miniconda3/envs/jdaviz1.1/lib/python3.9/site-packages/specutils/spectra/spectrum_mixin.py in _new_spectral_wcs(self, unit, velocity_convention, rest_value)
    280 
    281         if 'original_unit' not in self._meta:
--> 282             meta['original_unit'] = self.wcs.unit[0]
    283 
    284         # Create the new wcs object

AttributeError: 'WCS' object has no attribute 'unit'

**Comment by ibusko** [comment]
This is caused by function `cubeviz.load_data()` relying on the spectral cube package to read spectral cubes. `spectral_cube` uses class `astropy.wcs.wcs.WCS`, which doesn't have a `unit` attribute. 

On the other hand, when reading a 1-D spectrum such as with `specviz.load_spectrum()`, `Spectrum1D` uses class `specutils.utils.wcs_utils.gwcs_from_array.<locals>.SpectralGWCS`, which DOES have a `unit` attribute.

This problem should go away when the migration out of `spectral_cube` is complete.

**Comment by ibusko** [comment]
In an attempt to solve the problem, I added code to `cubeviz-data-parser` to explicitly call the `Spectrum1D` constructor (with the file name as argument) instead of allowing it to open the file and call the `SpectralCube` constructor. That should force the build of the correct WCS instance (`specutils.utils.wcs_utils.gwcs_from_array.<locals>.SpectralGWCS`).

Indeed, that happens, but the end product is defective. The `Spectrum1D` constructor adds a `wcs` attribute to its product, with the correct class, but initialized to the wrong parameters (seems to be just defaults). This happens even if we add an explicit reference `wcs=wcs` to the constructor call. The passed `wcs` instance was correctly build and initialized by the caller code in `specutils/io/default_loaders/jwst_readers.py`, but the constructor ignores it and sticks the wrong instance to its product instead.

This would go unnoticed under most circumstances, but not when the glue code attempts to add the `Spectrum1D` instance just built, to its `data_collection`. The glue code checks for attribute `wcs.world_axis_names` and finds it wrongly initialized (the correct `wcs` was dropped off the table by the `Spectrum1D` constructor).

This causes the loading to fail. Here is what the constructor does:

![Untitled 4](https://user-images.githubusercontent.com/3577145/114095841-ed0f2180-988b-11eb-8796-56298e220bb4.jpg)

Inspecting the correct wcs instance (the one that got ignored), we see that `world_axis_names` is correctly initialized with the spectral cube actual data:

<img width="1455" alt="Untitled 2" src="https://user-images.githubusercontent.com/3577145/114096166-5abb4d80-988c-11eb-9d45-65b5204d3903.png">

This will require fixing in the `Spectrum1D` constructor. Or is this the intended behavior and the fix should be placed at an upper level (jwst parser code perhaps)?
