### ISSUE TITLE
JDAT-1222: Blinking/tabbing between images

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#520]
Blink one or more images in the same viewer.

https://jira.stsci.edu/browse/JDAT-1222

# Follow-up of #429 

- [ ] Note from @pllim: Where will the keyboard magic be documented? For instance, I wouldn't know pressing `b` will blink unless I watch that video.
- [ ] Also, will `b` be able to blink tabs too?

**Comment by astrofrog** [comment]
A checkable tool is like pan and zoom or the selection tools - once enable you can do something with e.g. the cursor or keyboard. A non-checkable tool is like the home icon - it does an action as you press it and then returns to not being selected. Does this make sense? (how to write these is documented at http://docs.glueviz.org/en/stable/customizing_guide/toolbar.html)

As I mentioned yesterday, continuously blinking the images requires some kind of threading because we need to blink while also checking for click events to make sure you can stop the tool (hence my alternative suggestions above).

**Comment by pllim** [comment]
> some kind of threading

I thought we were told not to worry about threading but I guess blocking click event to stop blinking is a deal breaker. 😆

**Comment by pllim** [comment]
> An alternative is to implement a Tool (non-checkable) that when clicked will blink the images once, and again could have a tooltip that tells the user they can also press b to blink (anytime, not just when the tool is checked).

I slightly prefer this one. I'll give that a stab today.

**Comment by astrofrog** [comment]
Sounds good! Let me know if you have any questions!
