### ISSUE TITLE
Develop a Gaussian smoothing sidebar plugin

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#53]
One of the features needed for the cubeviz prototype is a sidebar that provides tools for doing Gaussian smoothing of the data. It wasn't clear to me if this should be spectral or spatial smoothing, but I would imagine that both could be useful, so this could be a parameter in the sidebar?

**Comment by hcferguson** [comment]
On the spectral-smoothing side of things, we had a paradigm in the Qt cubevis where you could do this (or other kinds of operations such as fitting) in your specviz window and then apply to all spaxels.

**Comment by nmearl** [comment]
That was more-or-less a paradigm due to the way we just sort of "stuck" specviz inside cubeviz. It doesn't necessarily need to operate that way (and I'd argue we don't want any tools specifically pinned to a particular viewer.)

That said, it's trivial to add new trays to the sidebar, and I think both spatial and spectral smoothing should probably be operations within the same tray window.
