### ISSUE TITLE
"IMPORT +" button should open file dialog

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#546]
Ideally the `IMPORT +` button should open up a file picker dialog. But right now, all I see is a plain text field and you have to manually type in the full path. On Linux, I cannot even copy-paste the path from terminal, making the button not very user friendly.

**Comment by pllim** [comment]
I was told this is impossible due to browser security restrictions.

I think the next best thing is to remove this button altogether and rely more on the CLI or Pythonic commands inside a notebook.

**Comment by duytnguyendtn** [comment]
Wait a sec, this is the first I've ever heard of any "browser security restrictions" stopping a file picker. @nmearl had a PR out ( #186 ) to actually implement exactly this, and I was hoping to take a stab at it sometime soon.

I'm probably one of the strongest proponents for the Desktop mode layout; if we want to replace SAO DS9, I really see the ability to select images via file dialog as imperative to our goal (That on top of releasing installation binaries, but that's a discussion for another day ;P)

**Comment by pllim** [comment]
As long as we're not introducing security holes in accomplishing it.

**Comment by astrofrog** [comment]
To clarify the issue here, @nmearl's PR #186 works fine BUT this currently uploads data to the browser rather than allowing jdaviz to access the file on disk (this is the security restriction). However, a solution to work around this is to implement a file browser in JS which communicates with the Python kernel to list directories and access files. However this is a bit more work as it requires implementing a file browser! (unless we can find an existing implementation).

**Comment by pllim** [comment]
Come to think of it, even `jupyter notebook` doesn't have a full-fledged file browser. It only lets you see the files in the working directory and sub-directories. 💭

**Comment by eteq** [comment]
Copying something here from Slack that's related to #573:

Follow-on about the discuission re: file pickers (esp. @trobitaille and @mariobuikhuizen ) - Definitely @trobitaille "non-native" picker is way better than the existing type-a-path approach.  But I think the end state we want is
1. A native file picker (I know this is hard due to browser security restrictions!)
2. An auto-upload tool
3. A way to drop in a URL which works basically like the auto-upload

Whether we want these as like three "tabs" in the import button, auto-selected somehow based on environment (i.e. 2/3 in jupyterhub, 1/3 in the desktop, none in the notebook, etc), I'm not sure, but I think those are all things we've realized we want.

On Native File Picker, @trobitaille pointed out the "qt shim" solution, which is definitely not a good choice relative to ipyfilechooser. But I thought the other solution for the desktop interface was to use electron - i.e., my impression from Nick was that this is one of the key reasons to be thinking about electron (that it allows that kind of "interact with the local machine" stuff)

**Comment by eteq** [comment]
(my comment just above *may* be out-of-scope for this issue.  I can make a follow-up if we think #573 or #186 close this out

**Comment by pllim** [comment]
Might be a duplicate of #156
