### ISSUE TITLE
[FEAT] Imviz: Should coordinate display be 0- or 1-indexed?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#590]
### Description

Currently, the `x` and `y` shown is 0-index. In DS9, it is 1-indexed.

### Additional context

A follow up of https://github.com/spacetelescope/jdaviz/pull/557#pullrequestreview-648376970

**Comment by drlaw1558** [comment]
Whichever is chosen, it would be helpful to be made clear.  The pipeline uses a 0-indexed coordinate system, and as such that may be a convenient choice.  Note also that in the pipeline the origin is defined to be the center of a pixel rather than the corner; i.e., (0,0) is the center of the lower-left pixel.

**Comment by pllim** [comment]
Yes, I think currently it is also defined at the center of the pixel *and* 0-indexed. If we are okay with this, it might just be a matter of documentation.

**Comment by pllim** [comment]
This is also being discussed among other issues at #600

**Comment by pllim** [comment]
Not complains about them being zero indexed and the API doc will clearly indicate they are zero indexed.
