### ISSUE TITLE
Need to stack Snackbar messages

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#688]
Following discussions in https://github.com/spacetelescope/jdaviz/issues/600#issuecomment-859587985 , there is a need to be able to stack multiple "snackbar" messages so they don't clobber each other.

This feature is needed so that the message added in #680 will actually show.

cc @eteq @ibusko 

[🐱](https://jira.stsci.edu/browse/JDAT-1559)

**Comment by ibusko** [comment]
Besides the new snackbar added in #680, there are others already being stacked out of view by the app. One example I could see was a message issued right after something is added to a data collection, like "xxx was successfully added". This is clobbered by a subsequent message that says "xxx was successfully loaded". Maybe that's OK since during certain workflows these won't be issued one right after the other. In any case, anything emitted by the parsers will get clobbered by the "successfully loaded" message.

**Comment by pllim** [comment]
Fixed in #701
