### ISSUE TITLE
Implement consistent default data labels across jdaviz

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#727]
The default data labels assigned when loading data into helpers are inconsistent with each other.  Here are example data labels for each helper:
- Cubeviz: `jw00675-o019_t010_miri_ch3-long_s3d.fits[SCI]`
- Specviz: `specviz_data|kj-y%1$aT6sg&5gVNyM|`
- Specviz2d: `Spectrum2D` and `Spectrum1D`
- Mosviz: `2D Spectrum i`, `1D Spectrum i` , `MOS Table`
- Default: `jw00675-o019_t010_miri_ch3-long_s3d[SCI]`

Should these be standardized in any way?  While the data file to label mapping is neatly handled in the helpers during the helper's `load_data/spectrum` stage, this may make it more difficult for users to do similar things things programmatically with a default viewer.  At least without a more exposed API to provide users the machinery to do it themselves.  

[🐱](https://jira.stsci.edu/browse/JDAT-1624)

**Comment by pllim** [comment]
But you can already access available data labels via `app.data_collection.labels`. I am not sure how easy it is to standardize given the vastly different data formats that each configuration can handle.

**Comment by havok2063** [comment]
I think the labels are being defined by Jdaviz so Jdaviz could enforce some naming scheme.  Originally I think all the labels in all the helpers had a `file_stem[ext]` label syntax and now labels are different for every helper.  The `add_data_to_viewer` originally allowed for a user to provide a reference filename and extension name, to avoid data label look.  That functionality is now either broken or made much more complicated.  

The helpers classes ostensibly take care of this, since their `load_data` methods handle 1. sorting out data names and labels, and 2. loading the data into the application and 3. loading the data into the proper viewer.  But with the `default` Application, users need to perform those steps themselves using `load_data` and `add_data_to_viewer`.  All this is just to say that there's some work needed to improve the programmatic navigation of Jdaviz to make it fully customizable.  And I think this ticket falls in that category.

**Comment by pllim** [comment]
@havok2063 , how would you like this standardized? It is really only possible if a filename is given. For example, when you load a pure Numpy array into Imviz, there is no way for Imviz to be able to turn that into a coherent naming scheme.

**Comment by havok2063** [comment]
Ahh yeah true I forgot about cases when the input is already an in-memory python object.   I think the more common input for users will be to provide a filepath though, as it's the workflow with the least amount of steps involved.  And that's how all the example notebooks, docs, and demos for the Jdaviz helpers are written.  But yeah we should have some standards for different cases.  So maybe something like the following, when the input is:  

- a filepath -  label is `filename_stem[ext]`
- a data array - label is `array_[ndim]d`. or `array_[shape]`
- a Spectrum1D object - label is `Spectrum1D_[size or shape]`
- a SpectrumList object - label is `SpectrumList_[size or shape or number]`

**Comment by pllim** [comment]
That is a reasonable proposal. I can see a generic utility function to apply such naming scheme given the input type, and all the parsers can just call this function for a consistent naming scheme. However, this can easily take half a spring of dev time, so probably needs to be added into the backlog or something...

**Comment by pllim** [comment]
I think @duytnguyendtn and @javerbukh said this morning that this could be part of a larger unified parser refactor. Duy mentioned a ticket number but I don't remember now. 😬

**Comment by pllim** [comment]
I created https://jira.stsci.edu/browse/JDAT-1624 for this. Also updated the title to be more "active".

**Comment by javerbukh** [comment]
So I went through all our different parsers and noted what object types are accepted for loading. Here is that list:
1. Cubeviz
    1. File object as a string
    2. Parse hdulist
    3. Fileobj is Spectrum1D, shape 3 and 1
    4. Else is unsupported
2. Does default have a parser?
3. Imviz
    1. String (file)
    2. HDUlist
    3. fits.ImageHDU, fits.CompImageHDU, fits.PrimaryHDU
    4. NDData
    5. np.array
4. Mosviz
    1. X1d, c1d
    2. S2d
    3. Images
    4. SpectrumCollection
    5. Spectrum1D
    6. SpectrumList
    7. HDUList
    8. DATAMODL
5. Specviz
    1. Spectrum1D
    2. SpectrumList
6. Specviz2D
    1. Filename
    

So we need to have data labels for the following object types:
- [ ] Filename
- [ ] HDUList
- [ ] Spectrum1D, shape 1d and 3d
- [ ] NDData
- [ ] np.array
- [ ] Images (PNG, JPG)
- [ ] DATAMODL

I propose we leave comments with potential data labels for each type and then vote on which paradigm the team prefers going forward.

**Comment by javerbukh** [comment]
If a user adds their data with a data_label, that data_label will be preferred in all cases and will appear as "data_label", else:
- Filename: filename_[ext] ... "contents_[FLUX]"
- HDUList: HDUList.name ... "SCI"
- Spectrum1D, shape 1s and 3d: Spectrum1D_(size or shape) ... "Spectrum1D_(10, 10, 100)"
- NDData: NDData_(size or shape) ... "NDData_(10, 10)"
- np.array: Array_(size or shape) ... "Array_(1000)"
- Images (PNG, JPG): Image_[file type] ... "Image_[PNG]"
- DATAMODL: DATAMODL_(size or shape) ... "DATAMODL_(10, 10, 100)"

There is also the issue of duplicate names. Do we want to use numbers from 1+, exact time, random UUID, etc.? My first instinct would be to use time since the user will know the order they added data and can distinguish which data is which based on that. We could also take a radically different approach and add random words after the default label, i.e. "Spectrum1D_(10, 10, 100)_pizzaapplecoffee".

**Comment by pllim** [comment]
My notes for Imviz:

* Most of the parsing behavior is intentional (like appending `[DATA]` vs `[SCI,1]`) because Imviz understand both FITS and ASDF-in-FITS.
* You need to take account of the EXTVER too because EXTNAME is not unique and Imviz allows loading all valid extensions using wildcard.

General comments:

* I would be in favor of getting rid of UUID altogether.
* 👎 on random words. We are not Wordle.
* Just how useful is the shape info in the data label? Do we really need that? I wouldn't add a lot of parenthesis and square brackets for fun, they are not fun to type out by hand when one needs to access the data labels after loading. The square brackets currently used to denote extensions are there for "historical" reasons.
* Maybe we can use sequence numbers like Subsets.

https://github.com/spacetelescope/jdaviz/blob/1639526e2bf6d2df39e6f35596a6a591e83d7f0f/jdaviz/core/helpers.py#L672

And how to use it here:

https://github.com/spacetelescope/jdaviz/blob/1639526e2bf6d2df39e6f35596a6a591e83d7f0f/jdaviz/configs/imviz/plugins/parsers.py#L135

**Comment by rosteen** [comment]
I agree on the thumbs-down to random words. My vote for duplicate labels is appending numbers, maybe with brackets around them - I don't mind brackets personally and it might distinguish the number we added better than an underscore. I don't feel strongly about that though. That said, I don't think I like adding the shape of the array to the label. 👎 from me on UUID as well.

How about instead of shape, all the ones currently using shape just use integer index (`Array_1`, `NDData_1`, etc)? Even with shapes we could run into multiple loaded objects having the same shape, may as well jump right to a number index.
