### ISSUE TITLE
Imviz astrowidgets API to work on tiled viewers

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#741]
Currently `viewer-1` is hardcoded everywhere. Now that #722 is merged, user should be able to use `astrowidgets` API on tiled viewers.

This should only be worked on after the following remaining astrowidgets API are implemented:

* #715 
* #716 
* #717 
* #718 
* #719

[🐱](https://jira.stsci.edu/browse/JDAT-1636)

**Comment by pllim** [comment]
@eteq suggested maybe we should move the API from

https://github.com/spacetelescope/jdaviz/blob/d0c2ce00041101e636ed71c97e7eb00047ba96df/jdaviz/configs/imviz/helper.py#L27

to 

https://github.com/spacetelescope/jdaviz/blob/d0c2ce00041101e636ed71c97e7eb00047ba96df/jdaviz/configs/imviz/plugins/viewers.py#L13

I think that makes sense, but do we have enough time left to do this? I think it needs at least half a sprint, uninterrupted. But then again, it is better to get this done before the first release.

**Comment by eteq** [comment]
@pllim and I discussed this a bit out-of-band after thinking a bit more about #827.  So with that in mind I wanted to make a case for option 3 from above:

The `astrowidgets` API is pretty focused on one "viewer" - and I think keeping it that way will make it easier to write fairly generic code using astrowidgets and simplify implementation of backends for it.  So that argues pretty strongly against 1. 

My main issue with 2 is that it leads to workflows more or less like this:
```
imviz.set_active_viewer('imviz-1')
imviz.do_something_in_code(...)

imviz.set_active_viewer('imviz-2')
imviz.do_something_in_code(...)

... lots of other code in a notebook, followed by  user does some UI interaction where they click on viewer 1 ...

imviz.do_something_in_code_intended_for_viewer1(...)

```
that is, the user has to mentally keep track of what the "code" and "UI" are doing separately.  Whereas in case 3 they do:
```
imviz.get_viewer('imviz-1').do_something_in_code(...)

imviz.get_viewer('imviz-2').do_something_in_code(...)

... lots of other code in a notebook, followed by  user does some UI interaction where they click on viewer 1 ...

imviz.get_viewer('imviz-1').do_something_in_code_intended_for_viewer1(...)
```
there's no way to get confused, because you *have* to choose the right viewer explicitly.

**Comment by eteq** [comment]
Oh, and @pllim pointed out there's some rough edges option 3 has to work around, most notably the fact that some of the astrowidget API choices add marker data to glue which then would be visible in the *other* viewers. But I personally think that's ok because the individual viewers can still keep track of which are "their" markers. And it's ok if users can see those in the UI, just so long as that doesn't "leak" into astrowidgets code.

**Comment by pllim** [comment]
Thanks for a nice summary, @eteq !

I also want to make it clear that I have strong opinion that we should decide on Option 2 _or_ Option 3 _before_ MVP release. I am very much against Option 2 first and then Option 3 refactor, because that introduces maintenance and user experience nightmares.
