### ISSUE TITLE
[BUG] Imviz: get_interactive_regions() returns error when data has GWCS

### ISSUE THREAD

**Issue by camipacifici** [spacetelescope/jdaviz#781]
**Dev notes**

The "proper way" to fix this is blocked by:

* astropy/astropy#11727
* glue-viz/glue-astronomy#38

But we don't need them for the "hacky way".

**Describe the bug**
I opened a JWST image with WCS, created a region, then from the notebook I called `imviz.get_interactive_region()` and I got the following traceback:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/js/kn36084x6k988161dxy2fwlw0001hl/T/ipykernel_39555/2721024945.py in <module>
----> 1 imviz.get_interactive_regions()

~/opt/miniconda3/envs/pr778/lib/python3.8/site-packages/jdaviz/configs/imviz/helper.py in get_interactive_regions(self)
    509 
    510         """
--> 511         return self.app.get_subsets_from_viewer('viewer-1')
    512 
    513 

~/opt/miniconda3/envs/pr778/lib/python3.8/site-packages/jdaviz/app.py in get_subsets_from_viewer(self, viewer_reference, data_label, subset_type)
    488         """
    489         viewer = self.get_viewer(viewer_reference)
--> 490         data = self.get_data_from_viewer(viewer_reference,
    491                                          data_label,
    492                                          cls=None)

~/opt/miniconda3/envs/pr778/lib/python3.8/site-packages/jdaviz/app.py in get_data_from_viewer(self, viewer_reference, data_label, cls, include_subsets)
    431                     #  output data type
    432                     elif len(layer_data.shape) == 2:
--> 433                         layer_data = layer_data.get_object(cls=CCDData)
    434 
    435                     data[label] = layer_data

~/opt/miniconda3/envs/pr778/lib/python3.8/site-packages/glue/core/data.py in get_object(self, cls, **kwargs)
    287         handler, _ = data_translator.get_handler_for(cls)
    288 
--> 289         return handler.to_object(self, **kwargs)
    290 
    291     @property

~/opt/miniconda3/envs/pr778/lib/python3.8/site-packages/glue_astronomy/translators/ccddata.py in to_object(self, data_or_subset, attribute)
     42             wcs = None
     43         else:
---> 44             raise TypeError('data.coords should be an instance of Coordinates or WCS')
     45 
     46         if isinstance(attribute, str):

TypeError: data.coords should be an instance of Coordinates or WCS
```
**Expected behavior**
Return the region. This actually works on an image with no WCS.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - jupyter core     : 4.7.1
 - jupyter-notebook : 6.4.3

**Package versions (please complete the following information):**

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09) 
[Clang 11.1.0 ]
Numpy 1.21.1
astropy 4.3.post1
specutils 1.3
spectral-cube 0.5.0
pyyaml 5.4.1
click 8.0.1
asteval 0.9.25
idna 2.10
traitlets 5.0.5
bqplot 0.12.30
bqplot-image-gl 1.4.4
glue-core 1.1.0
glue-jupyter 0.7
glue-astronomy 0.2
echo 0.5
ipyvue 1.5.0
ipyvuetify 1.8.1
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
voila 0.2.10
vispy 0.7.3
Jdaviz 1.2.dev398+gf691d7a

[🐱](https://jira.stsci.edu/browse/JDAT-1670)

**Additional context (e.g. data files)**
[Image](https://stsci.box.com/s/ox91bao6ijfqymqebkg6dmugurc0n5vr)

**Comment by pllim** [comment]
This one is a little complicated because it calls this:

https://github.com/spacetelescope/jdaviz/blob/8019780dcb4d9198b2bb4b1b5a0d7392d4508969/jdaviz/app.py#L456

that calls this:

https://github.com/spacetelescope/jdaviz/blob/8019780dcb4d9198b2bb4b1b5a0d7392d4508969/jdaviz/app.py#L356

that forces CCDData on anything that is 2D:

https://github.com/spacetelescope/jdaviz/blob/8019780dcb4d9198b2bb4b1b5a0d7392d4508969/jdaviz/app.py#L432-L433

And I don't think any of this is needed anyway to grab just the Subset, but the way this was currently implemented was as suggested by SME. 🤷 

So, I can see two different ways to solve this... PO needs to decide and queue this for the Scrum work. Also, is this critical to fix for MVP?

### The long way

Fix astropy/astropy#11727 and glue-viz/glue-astronomy#38

### The short but hacky way

Re-implement `imviz.get_interactive_regions()` to not use `app.get_subsets_from_viewer()`.
