### ISSUE TITLE
DOC: Do not hardcode /tmp in Mosviz example notebook

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#869]
As suggested by @ojustino and @astrofrog , the example notebook needs to be updated to not hardcode the temporary directory. Otherwise, when upstream data changed, people are going to be accidentally using the old data still and get confused.

[🐱](https://jira.stsci.edu/browse/JDAT-1767)

**Comment by ojustino** [comment]
I've forgotten this conversation and don't see a difference between the current data download procedure and its counterpart [in a commit](https://github.com/spacetelescope/jdaviz/blob/252788373ffa6f611d02bff8a84f06d52d36911e/notebooks/MosvizExample.ipynb) from around the time this issue was created. However, given that neither uses a hard-coded `/tmp` path (instead opting for `tempfile.gettempdir()`), do we consider the current approach general enough to close this issue?

**Comment by duytnguyendtn** [comment]
Agreed; I think this issue is stale; I don't see any hardcoding to /tmp in either mosviz example notebooks

**Comment by pllim** [comment]
Yeah, I think we can close. Thanks for the ping!
